#!/usr/bin/env bash

# update aptitude
sudo ./bin/sudo-commands 

# install rbenv
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
source ~/.bashrc
echo "================== RBENV VERSION =================="
rbenv -v

# install ruby
rbenv install 2.7.1
rbenv global 2.7.1
rbenv rehash
echo "================== RUBY VERSION =================="
ruby -v

# install bundler
gem install bundler
echo "================== RUBY VERSION =================="
bundle --version

# install nvm
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
source ~/.profile 
echo "================== NVM VERSION =================="
nvm -v

# install node
nvm install node 
echo "================== NODE VERSION =================="
node --version

# install yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt install --no-install-recommends yarn
echo "================== YARN VERSION =================="
yarn --version
